todolist/models.py
# -*- coding=utf-8 -*-

# Author: D-zilch
# Datetime: 2020/4/6 12:22
# Product: PyCharm
# Project: todolist


from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from todolist.ext import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(24), unique=True, nullable=False)
    password_hash = db.Column(db.String(128))
    items = db.relationship("Item", back_populates="user", cascade="all")

    def set_password(self, password: str):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)


class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    user = db.relationship("User", back_populates="items")
    title = db.Column(db.String(64), nullable=False)
    status = db.Column(db.Integer, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.utcnow)

todolist/forms.py
# -*- coding=utf-8 -*-

# Author: D-zilch
# Datetime: 2020/4/6 12:22
# Product: PyCharm
# Project: todolist


from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, RadioField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError
from todolist.models import User


class RegisterForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(1, 24)])
    password = PasswordField("Password", validators=[DataRequired(), Length(1, 24)])
    password2 = PasswordField(
        "Repeat password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Register")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError("Please use a different username.")


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(1, 24)])
    password = PasswordField("Password", validators=[DataRequired(), Length(1, 24)])
    remember = BooleanField("Remember me")
    submit = SubmitField("Login")


class ItemForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(1, 64)])
    status = RadioField(
        "Status", validators=[DataRequired()], choices=[("1", "是"), ("0", "否")]
    )
    submit = SubmitField("Submit")

todolist/__init__.py
from flask import Flask
from todolist.ext import db, login_manager, bootstrap, csrf, moment
from todolist.blueprints.auth import auth_bp
from todolist.blueprints.todo import todo_bp


app = Flask("todolist")
app.config.from_pyfile("config.py")
db.init_app(app)
bootstrap.init_app(app)
login_manager.init_app(app)
csrf.init_app(app)
moment.init_app(app)

app.register_blueprint(auth_bp)
app.register_blueprint(todo_bp)

from todolist import commands, errors

todolist/blueprints/__init__.py
# -*- coding=utf-8 -*-

# Author: D-zilch
# Datetime: 2020/4/6 13:01
# Product: PyCharm
# Project: todolist

todolist/blueprints/auth.py
# -*- coding=utf-8 -*-

# Author: D-zilch
# Datetime: 2020/4/6 13:01
# Product: PyCharm
# Project: todolist


from flask import Blueprint, redirect, render_template, url_for, flash
from flask_login import login_required, logout_user, login_user, current_user
from todolist.ext import db
from todolist.models import User
from todolist.forms import RegisterForm, LoginForm


auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if current_user.is_authenticated:
        return redirect(url_for("todo.index"))
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Register success.")
        return redirect(url_for(".login"))
    return render_template("register.html", form=form)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for("todo.index"))
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        user = User.query.filter_by(username=username).first()
        if user:
            if user.validate_password(password):
                login_user(user, remember)
                flash("Login success.")
                return redirect(url_for("todo.index"))
            else:
                flash("Invalid username or password.")
        else:
            flash("No account", "warning")
    return render_template("login.html", form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logout success.")
    return redirect(url_for(".login"))

todolist/blueprints/todo.py
# -*- coding=utf-8 -*-

# Author: D-zilch
# Datetime: 2020/4/6 13:02
# Product: PyCharm
# Project: todolist


from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from todolist.forms import ItemForm
from todolist.models import Item
from todolist.ext import db


todo_bp = Blueprint("todo", __name__)


@todo_bp.route("/", methods=["GET"])
@login_required
def index():
    form = ItemForm()
    todolist = Item.query.filter_by(user_id=current_user.id).all()
    return render_template("index.html", todolist=todolist, form=form)


@todo_bp.route("/", methods=["POST"])
@login_required
def add_item():
    form = ItemForm()
    if form.validate_on_submit():
        title = form.title.data
        status = form.status.data
        item = Item(user=current_user, title=title, status=status)
        db.session.add(item)
        db.session.commit()
        flash("Item Added.")
    return redirect(url_for(".index"))


@todo_bp.route("/delete/<int:item_id>")
@login_required
def delete_item(item_id):
    item = Item.query.get_or_404(item_id)
    db.session.delete(item)
    db.session.commit()
    flash("Item Deleted.")
    return redirect(url_for(".index"))


@todo_bp.route("/change/<int:item_id>", methods=["GET", "POST"])
@login_required
def change_item(item_id):
    form = ItemForm()
    item = Item.query.get_or_404(item_id)
    if form.validate_on_submit():
        item.title = form.title.data
        item.status = form.status.data
        db.session.commit()
        flash("Item Changed.")
        return redirect(url_for(".index"))

    form.title.data = item.title
    form.status.data = str(item.status)
    return render_template("modify.html", form=form)

todolist/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}My TODO List{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse container">
        <div class="navbar-header"> <a class="navbar-brand" href="{{ url_for('todo.index') }}">TODO</a> </div>
        <!-- logout links -->
        {% if current_user.is_authenticated %}
            <ul class="nav navbar-nav pull-right">
                <li><a class="btn" href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
        {% endif %}
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <!-- flash message -->
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">close</span></button>
            {{ message }}
        </div>
        {% endfor %}

        <!-- body block -->
        {% block page_content %} {% endblock %}
    </div>
{% endblock %}



{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock scripts %}

todolist/templates/bootstrap/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
<!--    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">-->
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

todolist/templates/index.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block page_content %}
<table class="table table-hover">
    <thead>
        <th class="active">No</th>
        <th class="active">描述</th>
        <th class="active">是否完成</th>
        <th class="active">创建时间</th>
        <th class='active'>操作</th> 
    </thead>
    <tbody>
        {% for item in todolist %}

            <!-- tr -->
            {% if item.status %} <tr class="success">
            {% else %} <tr class="info"> {% endif %}
                <td>{{ loop.index }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.status }}</td>
                <td>{{ moment(item.create_time).format('YYYY-MM-DD HH:mm:ss') }}</td>
                <td>
                    {% if item.status %}
                    <a href="{{ url_for('todo.delete_item', item_id=item.id) }}" class="btn btn-danger" role ="button">删除</a>
                    {% else %}
                    <a href="{{ url_for('todo.change_item', item_id=item.id) }}" class="btn btn-success" role ="button">修改</a>
                    {% endif %}
                </td>

            </tr>
        {% endfor %}

    </tbody>
</table>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"> ADD </button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog"> <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="center">Add a new todo list</h4>
      </div>

      <div class="modal-body">
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  {{ render_form(form, form_type="horizontal") }}
              </div>
          </div>
      </div> <!-- modal body -->

    </div> </div>
</div>


{% endblock %}

todolist/templates/login.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block page_content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2 class="form-sign-in-heading">Please sign in</h2>
        {{ render_form(form) }}
        <p>New User?<a href="{{ url_for('auth.register') }}">Click to Register!</a></p>
    </div>
</div>
{% endblock %}

todolist/templates/modify.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block page_content %}
<div class="row">
    <h4 class="modal-title" id="myModalLabel" align="center"></h4>
    <div class="col-md-8 col-md-offset-2"> {{ render_form(form, form_type="horizontal") }} </div>
</div>
{% endblock %}

todolist/templates/register.html
{% extends "base.html" %}
{% from "bootstrap/form.html" import render_form %}

{% block page_content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2 class="form-register-heading">Register your account</h2>
        {{ render_form(form) }}
    </div>
</div>
{% endblock %}